### ISSUE TITLE
No download link provided through the REST API /getProjectInfo endpoint

### ISSUE THREAD

**Issue by patrickscheper** [OpenScan-org/OpenScanCloud#2]
Seems that there is no download link in the _dlink_ property even through the documentation says there should be. I received my generated 3D model via email, and the **/getProjectInfo** endpoint provides a 200 OK response status code with "processing done" in the status body.

I received: `status: 200 body: {"dlink":"","status":"processing done","ulink":["-myuploadlink-"]}`

**Comment by OpenScanEu** [comment]
Yes, I removed the download link from the endpoint to increase security. The only way to access the resulting model is through the link in the email. 
I might change it at some point in the future, but for now I do not like the direct access to the data/link through the endpoint... I do not know whether it is just my paranoia or whether this is a valid point ^^
