### ISSUE TITLE
Docker Version

### ISSUE THREAD

**Issue by reslip1** [OpenScan-org/OpenScanCloud#3]
Is it possible to run your own version in docker?

**Comment by OpenScanEu** [comment]
Do you mean running the reconstruction or sending packages to the OpenScanCloud? Unfortunately, the first is not possible (yet), but sending packages to OSC is absolutely possible through the provided endpoints.

**Comment by RagingRoosevelt** [comment]
Running a self-hosted instance of the reconstruction service would be so handy.

If you're interested, I'd be willing to help get something working.  I have experience with Docker, Python, C#, React, & Vue, so I could probably figure out what I was looking at.

**Comment by OpenScanEu** [comment]
Sorry for the long inactivity, I am going to close this issue, since I do not see a possibility to provide a docker version at the moment or foreseeable future.

**Comment by RagingRoosevelt** [comment]
@OpenScanEu, do you expect there will be some other self-hostable version?  I think a lot of people are put off by the closed nature of requiring the cloud processing for a project claiming to be open.

**Comment by OpenScanEu** [comment]
Hi, i just published a blog post addressing this issue: https://www.openscan.eu/post/is-openscan-an-open-source-project

**Comment by RagingRoosevelt** [comment]
Thank you for posting that!  Previous communication had made it seem like it was hard to open source but that it was your intention to do so. 

I fully support your decision not to release OSC and I appreciate that it is clearly communicated now. Thank you for such a useful and ever-improving project.

**Comment by RagingRoosevelt** [comment]
Perhaps it might be worth renaming this repo to OpenScanCloudUploader to help avoid future confusion, though?
